from __future__ import annotations

import json
import os
import time
from datetime import datetime
from pathlib import Path

import streamlit as st

from forecast_runner import (
    OUTPUT_DIR,
    STATUS_FILE,
    LOCK_FILE,
    run_forecast,
    get_latest_day_images,
)

st.set_page_config(
    page_title="ข้อมูลพยากรณ์ปริมาณฝนจากแบบจำลอง ECMWF",
    page_icon="🌧️",
    layout="wide",
    initial_sidebar_state="collapsed",
)

# -----------------------------
# Minimal UI styling
# -----------------------------
st.markdown(
    """
    <style>
    .block-container {
        padding-top: 1.2rem;
        padding-bottom: 2rem;
        max-width: 1180px;
    }
    h1 { margin-bottom: 0.15rem; }
    .subtitle {
        color: #59636e;
        margin-bottom: 1.1rem;
    }
    .status-box {
        border: 1px solid #d9e1e8;
        border-radius: 10px;
        padding: 0.9rem 1rem;
        background: #fafcfe;
    }
    .small-note {
        color: #6b7280;
        font-size: 0.9rem;
    }
    </style>
    """,
    unsafe_allow_html=True,
)

GOOGLE_DRIVE_URL = os.getenv("GOOGLE_DRIVE_URL", "").strip()

STEPS = [
    "เตรียมระบบประมวลผล",
    "ดาวน์โหลดข้อมูลพยากรณ์จาก ECMWF",
    "เตรียมข้อมูลปริมาณฝน",
    "นำเข้าข้อมูลแผนการถ่ายภาพดาวเทียม",
    "คำนวณปริมาณฝนสะสม 24 ชั่วโมง",
    "จัดทำแผนที่พยากรณ์ Day 1–Day 10",
    "บันทึกผลการประมวลผล",
]


def load_status() -> dict:
    if not STATUS_FILE.exists():
        return {
            "running": False,
            "step": 0,
            "message": "Ready",
            "progress": 0,
            "updated_at": None,
            "error": None,
        }
    try:
        return json.loads(STATUS_FILE.read_text(encoding="utf-8"))
    except Exception:
        return {
            "running": False,
            "step": 0,
            "message": "Ready",
            "progress": 0,
            "updated_at": None,
            "error": None,
        }


def render_status(status: dict):
    st.subheader("สถานะการประมวลผล")
    progress = int(status.get("progress", 0))
    st.progress(max(0, min(progress, 100)) / 100)

    active_step = int(status.get("step", 0))
    running = bool(status.get("running", False))

    rows = []
    for idx, label in enumerate(STEPS, start=1):
        if idx < active_step:
            icon = "✅"
        elif idx == active_step and running:
            icon = "🔄"
        elif idx == active_step and not running and progress == 100:
            icon = "✅"
        else:
            icon = "○"
        rows.append(f"{icon} **{idx}. {label}**")

    st.markdown("\n\n".join(rows))

    message = status.get("message")
    if message:
        st.info(message)

    if status.get("error"):
        st.error(status["error"])

    if status.get("updated_at"):
        st.caption(f"ปรับปรุงสถานะล่าสุด: {status['updated_at']}")


def display_part_a():
    st.divider()
    st.header("ปริมาณฝนสะสม 24 ชั่วโมง")
    st.caption(
        "Satellite footprints and ground tracks are retained exactly in the map products generated by the forecast code."
    )

    images = get_latest_day_images()

    if not images:
        st.info("ยังไม่มีผลการพยากรณ์ กรุณาดำเนินการประมวลผลข้อมูลเพื่อจัดทำแผนที่ Day 1–Day 10")
        return

    days = sorted(images.keys())
    selected_day = st.radio(
        "ช่วงเวลาพยากรณ์",
        days,
        horizontal=True,
        label_visibility="collapsed",
    )

    image_path = images[selected_day]
    st.image(
        str(image_path),
        use_container_width=True,
        caption=image_path.name,
    )

    col1, col2 = st.columns([1, 1])
    with col1:
        st.caption(f"ผลการพยากรณ์: {selected_day}")
    with col2:
        try:
            ts = datetime.fromtimestamp(image_path.stat().st_mtime)
            st.caption(f"ปรับปรุงแผนที่ล่าสุด: {ts:%d %b %Y %H:%M}")
        except Exception:
            pass


# -----------------------------
# Header
# -----------------------------
st.title("ข้อมูลพยากรณ์ปริมาณฝนจากแบบจำลอง ECMWF")
st.markdown(
    '<div class="subtitle">ปริมาณฝนสะสม 24 ชั่วโมง และแผนการถ่ายภาพดาวเทียม SAR</div>',
    unsafe_allow_html=True,
)

status = load_status()
is_running = bool(status.get("running", False)) or LOCK_FILE.exists()

left, right = st.columns([1, 2])

with left:
    run_clicked = st.button(
        "▶ ดำเนินการประมวลผลข้อมูล",
        type="primary",
        use_container_width=True,
        disabled=is_running,
    )

with right:
    if is_running:
        st.warning("ระบบกำลังประมวลผลข้อมูล ไม่สามารถดำเนินการซ้ำในขณะนี้")
    elif status.get("progress") == 100 and not status.get("error"):
        st.success("การประมวลผลข้อมูลล่าสุดเสร็จสมบูรณ์")
    else:
        st.caption("สามารถดำเนินการประมวลผลได้โดยไม่ต้องเข้าสู่ระบบ")

if run_clicked:
    status_area = st.empty()

    def callback(step: int, progress: int, message: str):
        current = load_status()
        with status_area.container():
            render_status(current)

    try:
        run_forecast(callback=callback)
        st.success("ประมวลผลข้อมูลเสร็จสมบูรณ์")
        time.sleep(0.5)
        st.rerun()
    except Exception as exc:
        st.error(f"เกิดข้อผิดพลาดในการประมวลผล: {exc}")

render_status(load_status())
display_part_a()

st.divider()
st.caption("Dashboard แสดงเฉพาะข้อมูลปริมาณฝนสะสม 24 ชั่วโมง Day 1–Day 10")
