from __future__ import annotations

import json
import os
import time
from datetime import datetime
from pathlib import Path

import streamlit as st

from forecast_runner import (
    OUTPUT_DIR,
    STATUS_FILE,
    LOCK_FILE,
    run_forecast,
    get_latest_day_images,
)

st.set_page_config(
    page_title="ECMWF Thailand Rainfall Forecast",
    page_icon="🌧️",
    layout="wide",
    initial_sidebar_state="collapsed",
)

# -----------------------------
# Minimal UI styling
# -----------------------------
st.markdown(
    """
    <style>
    .block-container {
        padding-top: 1.2rem;
        padding-bottom: 2rem;
        max-width: 1180px;
    }
    h1 { margin-bottom: 0.15rem; }
    .subtitle {
        color: #59636e;
        margin-bottom: 1.1rem;
    }
    .status-box {
        border: 1px solid #d9e1e8;
        border-radius: 10px;
        padding: 0.9rem 1rem;
        background: #fafcfe;
    }
    .small-note {
        color: #6b7280;
        font-size: 0.9rem;
    }
    </style>
    """,
    unsafe_allow_html=True,
)

GOOGLE_DRIVE_URL = os.getenv("GOOGLE_DRIVE_URL", "").strip()

STEPS = [
    "Preparing system",
    "Downloading ECMWF forecast",
    "Reading and preparing rainfall data",
    "Loading satellite acquisition plans",
    "Processing 24-hour accumulated rainfall",
    "Generating Day 1–Day 10 maps",
    "Saving results to Google Drive",
]


def load_status() -> dict:
    if not STATUS_FILE.exists():
        return {
            "running": False,
            "step": 0,
            "message": "Ready",
            "progress": 0,
            "updated_at": None,
            "error": None,
        }
    try:
        return json.loads(STATUS_FILE.read_text(encoding="utf-8"))
    except Exception:
        return {
            "running": False,
            "step": 0,
            "message": "Ready",
            "progress": 0,
            "updated_at": None,
            "error": None,
        }


def render_status(status: dict):
    st.subheader("Forecast status")
    progress = int(status.get("progress", 0))
    st.progress(max(0, min(progress, 100)) / 100)

    active_step = int(status.get("step", 0))
    running = bool(status.get("running", False))

    rows = []
    for idx, label in enumerate(STEPS, start=1):
        if idx < active_step:
            icon = "✅"
        elif idx == active_step and running:
            icon = "🔄"
        elif idx == active_step and not running and progress == 100:
            icon = "✅"
        else:
            icon = "○"
        rows.append(f"{icon} **{idx}. {label}**")

    st.markdown("\n\n".join(rows))

    message = status.get("message")
    if message:
        st.info(message)

    if status.get("error"):
        st.error(status["error"])

    if status.get("updated_at"):
        st.caption(f"Last status update: {status['updated_at']}")


def display_part_a():
    st.divider()
    st.header("PART A — 24-Hour Accumulated Precipitation")
    st.caption(
        "Satellite footprints and ground tracks are retained exactly in the map products generated by the forecast code."
    )

    images = get_latest_day_images()

    if not images:
        st.info("No forecast maps are available yet. Press RUN FORECAST to generate Day 1–Day 10 products.")
        return

    days = sorted(images.keys())
    selected_day = st.radio(
        "Forecast day",
        days,
        horizontal=True,
        label_visibility="collapsed",
    )

    image_path = images[selected_day]
    st.image(
        str(image_path),
        use_container_width=True,
        caption=image_path.name,
    )

    col1, col2 = st.columns([1, 1])
    with col1:
        st.caption(f"Displayed product: {selected_day}")
    with col2:
        try:
            ts = datetime.fromtimestamp(image_path.stat().st_mtime)
            st.caption(f"Map updated: {ts:%d %b %Y %H:%M}")
        except Exception:
            pass


# -----------------------------
# Header
# -----------------------------
st.title("ECMWF Thailand Rainfall Forecast")
st.markdown(
    '<div class="subtitle">24-Hour Accumulated Precipitation • Thailand • Satellite acquisition overlays</div>',
    unsafe_allow_html=True,
)

status = load_status()
is_running = bool(status.get("running", False)) or LOCK_FILE.exists()

left, right = st.columns([1, 2])

with left:
    run_clicked = st.button(
        "▶ RUN FORECAST",
        type="primary",
        use_container_width=True,
        disabled=is_running,
    )

with right:
    if is_running:
        st.warning("A forecast is currently processing. Please wait for the current run to finish.")
    elif status.get("progress") == 100 and not status.get("error"):
        st.success("Latest forecast completed successfully.")
    else:
        st.caption("Anyone can run the forecast. No email or login is required on this page.")

if run_clicked:
    status_area = st.empty()

    def callback(step: int, progress: int, message: str):
        current = load_status()
        with status_area.container():
            render_status(current)

    try:
        run_forecast(callback=callback)
        st.success("Forecast completed successfully.")
        time.sleep(0.5)
        st.rerun()
    except Exception as exc:
        st.error(f"Forecast failed: {exc}")

render_status(load_status())
display_part_a()

st.divider()

if GOOGLE_DRIVE_URL:
    st.link_button(
        "📂 View all forecast products in Google Drive",
        GOOGLE_DRIVE_URL,
        use_container_width=True,
    )
else:
    st.info(
        "Google Drive link is not configured yet. "
        "Set GOOGLE_DRIVE_URL in the server environment or secret settings."
    )

st.caption(
    "Dashboard displays PART A only. Other 12-hour, 6-hour and 3-hour forecast products remain available in Google Drive."
)
